apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: will
    extra: cyn  
  name: will
spec:
  replicas: 10
  selector:
    matchLabels:
      app: will
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
     type: Recreate 
